# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ling's Life
email: lyngen@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  AI. MEG. EEG. ECG. PPG. Biomedical Engineering. Brain. Portfolio. Assistant Professor. Center for Brain, Mind, and Kaisei Sciences Research. Hiroshima University. Japan.
twitter_username: DrHuiLing
github_username: Hui-Ling
minimal_mistakes_skin: dirt
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Tokyo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Hui-Ling Chan"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "AI and Brain Scientist"
  links:
    - label: "LinkedIn"
      icon: "fab fa fa-linkedin-square"
      url: "https://www.linkedin.com/in/hui-ling-c-90026837/"
    - label: "Research Gate"
      icon: "fas fa-fw fa-link"
      url: "https://www.researchgate.net/profile/Hui-Ling_Chan"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DrHuiLing"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/lingcestmoi/"

excerpt: "This post should display a **header with an overlay image**, if the theme supports it."
header:
  overlay_image: /assets/images/IMG_1256_1.jpg
  caption: "No Pain, No Gain."
  actions:
    - label: "More Info"
      url: "https://unsplash.com"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/hui-ling-c-90026837/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DrHuiLing"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/lingcestmoi/"
    
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
